### 커넥터 목록 조회
GET 192.168.55.195:8083/connectors

### 특정 커넥터 상태조회
GET 192.168.55.195:8083/connectors/postgres-balance-success-connector/status

### 특정 커넥터 설정 조회
GET 192.168.55.195:8083/connectors/postgres-outbox-transfer-connector/config

### 커넥터 신규등록
POST 192.168.55.195:8083/connectors
Content-Type: application/json
{
}

### 특정 커넥터 설정값 변경
PUT 192.168.55.195:8083/connectors/postgres-outbox-transfer-connector/config
Content-Type: application/json
{
}

### 특정 커넥터 삭제
DELETE 192.168.55.195:8083/connectors/postgres-outbox-transfer-connector


### 커넥트 버전 확인
GET 192.168.55.195:8083/connector-plugins


